# Generated by Django 5.2.4 on 2025-07-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="projects_images/"),
        ),
    ]
